package DataDicitonaryDSL2.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class quickFixSwitchPlaces_QuickFix extends QuickFix_Runtime {
  public quickFixSwitchPlaces_QuickFix() {
    super(new SNodePointer("r:3423e4e2-9ce9-41e5-854b-6b75f9442cd9(DataDicitonaryDSL2.typesystem)", "1288904211232828998"));
  }
  public String getDescription(SNode node) {
    return "Switch places of first and second number.";
  }
  public void execute(SNode node) {
    int number = SPropertyOperations.getInteger(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number1$yR8I);
    SPropertyOperations.assign(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number1$yR8I, SPropertyOperations.getInteger(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number2$yWy5));
    SPropertyOperations.assign(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number2$yWy5, number);

  }

  private static final class PROPS {
    /*package*/ static final SProperty number1$yR8I = MetaAdapterFactory.getProperty(0xe42098a93fd7446cL, 0x8eb044c9c71b5415L, 0xbb4b2c0f5806237L, 0xbb4b2c0f5806238L, "number1");
    /*package*/ static final SProperty number2$yWy5 = MetaAdapterFactory.getProperty(0xe42098a93fd7446cL, 0x8eb044c9c71b5415L, 0xbb4b2c0f5806237L, 0xbb4b2c0f580623aL, "number2");
  }
}
